apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
     matchLabels:
       app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: tutum/hello-world
        name: hello
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            memory: "256Mi"
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress-external
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: test.codywimer.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello
          servicePort: 80
  tls:
    - hosts:
      - test.codywimer.com
      secretName: letsencrypt-prod-test